config/routes.rb
Rails.application.routes.draw do
  resources :rags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  resources :company_secrets, only: :index
  # Defines the root path route ("/")
  root "rags#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company_secret.rb
class CompanySecret < ApplicationRecord
end

app/models/rag.rb
class Rag < ApplicationRecord
  has_neighbors :embedding, normalize: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/company_secrets_controller.rb
class CompanySecretsController < ApplicationController
  def index
    if params[:query].present?
      database = CompanySecrets::Database.get
      results = database.ask(question: params[:query], k: 3)

      @answer = "Answer: #{results.chat_completion}"
    end
  end
end

app/controllers/rags_controller.rb
class RagsController < ApplicationController
  before_action :set_rag, only: %i[ show edit update destroy ]

  # GET /rags or /rags.json
  def index
    if params[:query].present?
      client = OpenAI::Client.new(access_token: ENV["OPENAI_API_KEY"])

      embedding = layer_norm client
        .embeddings(parameters: { model: "text-embedding-3-large", input: params[:query] })
        .dig("data", 0, "embedding")

      @rags = Rag.nearest_neighbors(:embedding, embedding, distance: "cosine").first(3)
    else
      @rags = Rag.all
    end
  end

  def layer_norm(embedding)
    mean = embedding.sum / embedding.size
    variance = embedding.map { |e| (e - mean) ** 2 }.sum / embedding.size
    stddev = Math.sqrt(variance + 1e-5)
    embedding.map { |e| (e - mean) / stddev }
  end

  # GET /rags/1 or /rags/1.json
  def show
  end

  # GET /rags/new
  def new
    @rag = Rag.new
  end

  # GET /rags/1/edit
  def edit
  end

  # POST /rags or /rags.json
  def create
    @rag = Rag.new(rag_params)

    respond_to do |format|
      if @rag.save
        format.html { redirect_to @rag, notice: "Rag was successfully created." }
        format.json { render :show, status: :created, location: @rag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rags/1 or /rags/1.json
  def update
    respond_to do |format|
      if @rag.update(rag_params)
        format.html { redirect_to @rag, notice: "Rag was successfully updated." }
        format.json { render :show, status: :ok, location: @rag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rags/1 or /rags/1.json
  def destroy
    @rag.destroy!

    respond_to do |format|
      format.html { redirect_to rags_path, status: :see_other, notice: "Rag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rag
      @rag = Rag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rag_params
      params.require(:rag).permit(:name, :description, :condition, :color, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rags_helper.rb
module RagsHelper
end

app/views/company_secrets/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Company Secrets" %>

  <p class="text-center w-full">
    <h1 class="text-4xl">The Library of Company Secrets<h1>
  </p>

  <div class="flex items-center w-full mt-8">
    <%= form_with url: "/company_secrets", method: :get, class: "w-full" do |form| %>
      <div class="flex w-full space-x-2 justify-between">
        <div class="text-2xl pt-3">
          <%= form.label :query, "Question:", class: "text-gray-700" %>
        </div>
        <div class="flex-grow pt-3">
          <%= form.text_field :query, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", value: params[:query] %>
        </div>
        <div>
          <%= form.submit "Search", class: "justify-center rounded-lg py-4 px-5 bg-blue-600 text-white block font-medium" %>
        </div>
      </div>
    <% end %>
  </div>

  <% if params[:query] %>
    <p class="text-2xl mt-12">
      <%=
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
        markdown.render(@answer).html_safe
      %>

    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rags" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/rags/_form.html.erb
<%= form_with(model: rag, class: "contents") do |form| %>
  <% if rag.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(rag.errors.count, "error") %> prohibited this rag from being saved:</h2>

      <ul>
        <% rag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :condition %>
    <%= form.number_field :condition, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :color %>
    <%= form.text_field :color, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :size %>
    <%= form.text_field :size, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/rags/_rag.html.erb
<div id="<%= dom_id rag %>" class="relative p-12 mt-12 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 flex justify-between">
  <div class="inline-block max-w-4xl">
    <p class="text-white">
      <strong class="font-medium">Name:</strong>
      <%= rag.name %>
    </p>

    <p class="mt-2 text-white">
      <strong class="font-medium">Description:</strong>
      <%= rag.description %>
    </p>

    <p class="mt-2 text-white">
      <strong class="font-medium">Condition:</strong>
      <%= rag.condition %>
    </p>

    <p class="mt-2 text-white">
      <strong class="font-medium">Color:</strong>
      <%= rag.color %>
    </p>

    <p class="mt-2 text-white">
      <strong class="font-medium">Size:</strong>
      <%= rag.size %>
    </p>

    <% if action_name == 'index' %>
      <%= link_to "More info", rag, class: "mt-4 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>

  <div class="inline-block max-w-sm ml-10">
    <img src="/rags/rag<%= rag.id%>.webp" />
  </div>
</div>

app/views/rags/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing rag</h1>

  <%= render "form", rag: @rag %>

  <%= link_to "Show this rag", @rag, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to rags", rags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rags/index.html.erb
<div class="w-full">
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <% content_for :title, "Rags" %>

    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Rags</h1>
      <%= link_to "New rag", new_rag_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <div class="flex items-center w-full mt-8">
      <%= form_with url: "/", method: :get, class: "w-full" do |form| %>
        <div class="flex w-full space-x-2 justify-between">
          <div class="text-2xl pt-3">
            <%= form.label :query, "Search for:", class: "text-gray-700" %>
          </div>
          <div class="flex-grow pt-3">
            <%= form.text_field :query, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", value: params[:query] %>
          </div>
          <div>
            <%= form.submit "Search", class: "justify-center rounded-lg py-4 px-5 bg-blue-600 text-white block font-medium" %>
          </div>
        </div>
      <% end %>
    </div>

    <div id="rags" class="min-w-full">
      <% @rags.each do |rag| %>
        <%= render rag %>
      <% end %>
    </div>
  </div>

  <div class="w-full inline-block my-24 text-center text-xl">
    <a href="/company_secrets/">Nothing to see in here</a>
  </div>
</div>

app/views/rags/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New rag</h1>

  <%= render "form", rag: @rag %>

  <%= link_to "Back to rags", rags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rags/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @rag %>

    <%= link_to "Edit this rag", edit_rag_path(@rag), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to rags", rags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this rag", @rag, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>